## 目录结构
#source:      .
#destination: ./_site
#plugins:     ./_plugins
#layouts:     ./_layouts
#data_source: ./_data
#collections: null
#
## 阅读处理
#safe:         false
#include:      [".htaccess"]
#exclude:      []
#keep_files:   [".git", ".svn"]
#encoding:     "utf-8"
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#
## 内容过滤
#show_drafts: null
#limit_posts: 0
#future:      true
#unpublished: false
#
## 插件
#whitelist: []
#gems:      []
#
## 转换
#markdown:    kramdown
#highlighter: rouge
#lsi:         false
#excerpt_separator: "\n\n"
#incremental: false
#
## 服务器选项
#detach:  false
#port:    4000
#host:    127.0.0.1
#baseurl: "" # does not include hostname
#
## 输出
#permalink:     date
#paginate_path: /page:num
#timezone:      null
#
#quiet:    false
#defaults: []
#
## Markdown 处理器
#rdiscount:
#  extensions: []
#
#redcarpet:
#  extensions: []
#
#kramdown:
#  auto_ids:       true
#  footnote_nr:    1
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
#  enable_coderay: false
#
#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style

# 站点设置
name: "CliffTop.Win"
title: "Cliff的工作室"
subtitle: "做有用的软件"
url: "https://www.clifftop.win"
about-name: "Cliff Han"
#about.facebook: "https://www.facebook.com/cliff.han.5"
about-linkedin: "http://www.linkedin.com/in/cliff-han"
about-github: "https://github.com/cliffhan"
about-blog: "http://blog.clifftop.win"
about-homeserver: "http://ct.cliffland.xyz"
about-mail: "mailto:56550744@qq.com"
